#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnutls
Version  : 3.4.4.1
Release  : 18
URL      : http://www.mirrorservice.org/sites/ftp.gnupg.org/gcrypt/gnutls/v3.4/gnutls-3.4.4.1.tar.xz
Source0  : http://www.mirrorservice.org/sites/ftp.gnupg.org/gcrypt/gnutls/v3.4/gnutls-3.4.4.1.tar.xz
Summary  : DANE security library for the GNU system
Group    : Development/Tools
License  : BSD-3-Clause BSD-3-Clause-Clear GFDL-1.3 GPL-3.0 GPL-3.0+ LGPL-2.0+ LGPL-2.1 LGPL-3.0
Requires: gnutls-bin
Requires: gnutls-lib
Requires: gnutls-doc
Requires: gnutls-locales
BuildRequires : bison
BuildRequires : docbook-xml
BuildRequires : gmp-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libidn-dev
BuildRequires : libtasn1-dev
BuildRequires : libxslt-bin
BuildRequires : nettle
BuildRequires : nettle-dev
BuildRequires : nettle-lib
BuildRequires : pkgconfig(p11-kit-1)
BuildRequires : pkgconfig(zlib)
BuildRequires : sed
BuildRequires : valgrind

%description
=============================================
GnuTLS implements the TLS/SSL (Transport Layer Security aka Secure
Sockets Layer) protocol.  GnuTLS is a GNU project.  Additional
information can be found at <http://www.gnutls.org/>.

%package bin
Summary: bin components for the gnutls package.
Group: Binaries

%description bin
bin components for the gnutls package.


%package dev
Summary: dev components for the gnutls package.
Group: Development
Requires: gnutls-lib
Requires: gnutls-bin

%description dev
dev components for the gnutls package.


%package doc
Summary: doc components for the gnutls package.
Group: Documentation

%description doc
doc components for the gnutls package.


%package lib
Summary: lib components for the gnutls package.
Group: Libraries

%description lib
lib components for the gnutls package.


%package locales
Summary: locales components for the gnutls package.
Group: Default

%description locales
locales components for the gnutls package.


%prep
%setup -q -n gnutls-3.4.4.1

%build
%configure --disable-static --with-default-trust-store-file=%{_sysconfdir}/ssl/cert.pem \
--with-default-trust-store-dir=%{_datadir}/ca-certs
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang gnutls

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/certtool
/usr/bin/crywrap
/usr/bin/gnutls-cli
/usr/bin/gnutls-cli-debug
/usr/bin/gnutls-serv
/usr/bin/ocsptool
/usr/bin/p11tool
/usr/bin/psktool
/usr/bin/srptool

%files dev
%defattr(-,root,root,-)
/usr/include/gnutls/abstract.h
/usr/include/gnutls/compat.h
/usr/include/gnutls/crypto.h
/usr/include/gnutls/dtls.h
/usr/include/gnutls/gnutls.h
/usr/include/gnutls/gnutlsxx.h
/usr/include/gnutls/ocsp.h
/usr/include/gnutls/openpgp.h
/usr/include/gnutls/pkcs11.h
/usr/include/gnutls/pkcs12.h
/usr/include/gnutls/pkcs7.h
/usr/include/gnutls/self-test.h
/usr/include/gnutls/system-keys.h
/usr/include/gnutls/tpm.h
/usr/include/gnutls/urls.h
/usr/include/gnutls/x509-ext.h
/usr/include/gnutls/x509.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files locales -f gnutls.lang 
%defattr(-,root,root,-)

