#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD605848ED7E69871 (ueno@gnu.org)
#
%define keepstatic 1
Name     : gnutls
Version  : 3.6.14
Release  : 67
URL      : https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.14.tar.xz
Source0  : https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.14.tar.xz
Source1  : https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.14.tar.xz.sig
Summary  : Transport Security Layer implementation for the GNU system
Group    : Development/Tools
License  : GPL-3.0+ LGPL-2.0+ LGPL-2.1
Requires: gnutls-bin = %{version}-%{release}
Requires: gnutls-info = %{version}-%{release}
Requires: gnutls-lib = %{version}-%{release}
Requires: gnutls-locales = %{version}-%{release}
Requires: gnutls-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : datefudge
BuildRequires : docbook-xml
BuildRequires : findutils
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : glibc-locale
BuildRequires : gmp-dev
BuildRequires : gmp-dev32
BuildRequires : gmp-lib32
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool-dev
BuildRequires : libidn-dev
BuildRequires : libidn-dev32
BuildRequires : libseccomp-dev
BuildRequires : libtasn1-dev
BuildRequires : libtasn1-dev32
BuildRequires : libunistring-dev
BuildRequires : libunistring-dev32
BuildRequires : libunistring-staticdev
BuildRequires : libxslt-bin
BuildRequires : net-tools
BuildRequires : nettle
BuildRequires : nettle-dev
BuildRequires : nettle-dev32
BuildRequires : nettle-lib
BuildRequires : nettle-lib32
BuildRequires : pkg-config
BuildRequires : pkgconfig(32libidn2)
BuildRequires : pkgconfig(32p11-kit-1)
BuildRequires : pkgconfig(libidn2)
BuildRequires : pkgconfig(p11-kit-1)
BuildRequires : sed
BuildRequires : texinfo
BuildRequires : util-linux
BuildRequires : util-linux-dev
BuildRequires : util-linux-staticdev
BuildRequires : valgrind
BuildRequires : valgrind-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: noversion.patch
Patch2: 0001-Don-t-run-trust-store-test-as-it-isn-t-in-the-buildr.patch

%description
ext/         -> Implementation of TLS extensions
auth/        -> Implementation of TLS authentication methods (DHE, SRP etc.)
accelerated/ -> Implementation of cipher acceleration

%package bin
Summary: bin components for the gnutls package.
Group: Binaries

%description bin
bin components for the gnutls package.


%package dev
Summary: dev components for the gnutls package.
Group: Development
Requires: gnutls-lib = %{version}-%{release}
Requires: gnutls-bin = %{version}-%{release}
Provides: gnutls-devel = %{version}-%{release}
Requires: gnutls = %{version}-%{release}

%description dev
dev components for the gnutls package.


%package dev32
Summary: dev32 components for the gnutls package.
Group: Default
Requires: gnutls-lib32 = %{version}-%{release}
Requires: gnutls-bin = %{version}-%{release}
Requires: gnutls-dev = %{version}-%{release}

%description dev32
dev32 components for the gnutls package.


%package doc
Summary: doc components for the gnutls package.
Group: Documentation
Requires: gnutls-man = %{version}-%{release}
Requires: gnutls-info = %{version}-%{release}

%description doc
doc components for the gnutls package.


%package extras
Summary: extras components for the gnutls package.
Group: Default

%description extras
extras components for the gnutls package.


%package info
Summary: info components for the gnutls package.
Group: Default

%description info
info components for the gnutls package.


%package lib
Summary: lib components for the gnutls package.
Group: Libraries

%description lib
lib components for the gnutls package.


%package lib32
Summary: lib32 components for the gnutls package.
Group: Default

%description lib32
lib32 components for the gnutls package.


%package locales
Summary: locales components for the gnutls package.
Group: Default

%description locales
locales components for the gnutls package.


%package man
Summary: man components for the gnutls package.
Group: Default

%description man
man components for the gnutls package.


%package staticdev
Summary: staticdev components for the gnutls package.
Group: Default
Requires: gnutls-dev = %{version}-%{release}

%description staticdev
staticdev components for the gnutls package.


%package staticdev32
Summary: staticdev32 components for the gnutls package.
Group: Default
Requires: gnutls-dev = %{version}-%{release}

%description staticdev32
staticdev32 components for the gnutls package.


%prep
%setup -q -n gnutls-3.6.14
cd %{_builddir}/gnutls-3.6.14
%patch1 -p1
%patch2 -p1
pushd ..
cp -a gnutls-3.6.14 build32
popd

%build
unset http_proxy
unset https_proxy
unset no_proxy
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596392143
export GCC_IGNORE_WERROR=1
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe $PGO_GEN"
export FCFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe $PGO_GEN"
export FFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe $PGO_GEN"
export CXXFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -pipe $PGO_GEN"
export LDFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe $PGO_GEN"
## pgo use
## -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden
## gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe $PGO_USE"
export FCFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe $PGO_USE"
export FFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe $PGO_USE"
export CXXFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe $PGO_USE"
export LDFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe $PGO_USE"
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#export CCACHE_DISABLE=1
## altflags_pgo end
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
%configure  --enable-guile=no --with-default-trust-store-dir=/var/cache/ca-certs/anchors --enable-shared --enable-static
make  %{?_smp_mflags}

make VERBOSE=1 V=1 %{?_smp_mflags} check || :
make clean
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
%configure  --enable-guile=no --with-default-trust-store-dir=/var/cache/ca-certs/anchors --enable-shared --enable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure  --enable-guile=no --with-default-trust-store-dir=/var/cache/ca-certs/anchors --enable-shared --enable-static   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
make %{?_smp_mflags} check || :
cd ../build32;
make %{?_smp_mflags} check || : || :

%install
export SOURCE_DATE_EPOCH=1596392143
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
%find_lang gnutls

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/certtool
/usr/bin/gnutls-cli
/usr/bin/gnutls-cli-debug
/usr/bin/gnutls-serv
/usr/bin/ocsptool
/usr/bin/p11tool
/usr/bin/psktool
/usr/bin/srptool

%files dev
%defattr(-,root,root,-)
/usr/include/gnutls/abstract.h
/usr/include/gnutls/compat.h
/usr/include/gnutls/crypto.h
/usr/include/gnutls/dtls.h
/usr/include/gnutls/gnutls.h
/usr/include/gnutls/gnutlsxx.h
/usr/include/gnutls/ocsp.h
/usr/include/gnutls/openpgp.h
/usr/include/gnutls/pkcs11.h
/usr/include/gnutls/pkcs12.h
/usr/include/gnutls/pkcs7.h
/usr/include/gnutls/self-test.h
/usr/include/gnutls/socket.h
/usr/include/gnutls/system-keys.h
/usr/include/gnutls/tpm.h
/usr/include/gnutls/urls.h
/usr/include/gnutls/x509-ext.h
/usr/include/gnutls/x509.h
/usr/lib64/libgnutls.so
/usr/lib64/pkgconfig/gnutls.pc
/usr/share/man/man3/dane_cert_type_name.3
/usr/share/man/man3/dane_cert_usage_name.3
/usr/share/man/man3/dane_match_type_name.3
/usr/share/man/man3/dane_query_data.3
/usr/share/man/man3/dane_query_deinit.3
/usr/share/man/man3/dane_query_entries.3
/usr/share/man/man3/dane_query_status.3
/usr/share/man/man3/dane_query_tlsa.3
/usr/share/man/man3/dane_query_to_raw_tlsa.3
/usr/share/man/man3/dane_raw_tlsa.3
/usr/share/man/man3/dane_state_deinit.3
/usr/share/man/man3/dane_state_init.3
/usr/share/man/man3/dane_state_set_dlv_file.3
/usr/share/man/man3/dane_strerror.3
/usr/share/man/man3/dane_verification_status_print.3
/usr/share/man/man3/dane_verify_crt.3
/usr/share/man/man3/dane_verify_crt_raw.3
/usr/share/man/man3/dane_verify_session_crt.3
/usr/share/man/man3/gnutls_aead_cipher_decrypt.3
/usr/share/man/man3/gnutls_aead_cipher_decryptv2.3
/usr/share/man/man3/gnutls_aead_cipher_deinit.3
/usr/share/man/man3/gnutls_aead_cipher_encrypt.3
/usr/share/man/man3/gnutls_aead_cipher_encryptv.3
/usr/share/man/man3/gnutls_aead_cipher_encryptv2.3
/usr/share/man/man3/gnutls_aead_cipher_init.3
/usr/share/man/man3/gnutls_alert_get.3
/usr/share/man/man3/gnutls_alert_get_name.3
/usr/share/man/man3/gnutls_alert_get_strname.3
/usr/share/man/man3/gnutls_alert_send.3
/usr/share/man/man3/gnutls_alert_send_appropriate.3
/usr/share/man/man3/gnutls_alpn_get_selected_protocol.3
/usr/share/man/man3/gnutls_alpn_set_protocols.3
/usr/share/man/man3/gnutls_anon_allocate_client_credentials.3
/usr/share/man/man3/gnutls_anon_allocate_server_credentials.3
/usr/share/man/man3/gnutls_anon_free_client_credentials.3
/usr/share/man/man3/gnutls_anon_free_server_credentials.3
/usr/share/man/man3/gnutls_anon_set_params_function.3
/usr/share/man/man3/gnutls_anon_set_server_dh_params.3
/usr/share/man/man3/gnutls_anon_set_server_known_dh_params.3
/usr/share/man/man3/gnutls_anon_set_server_params_function.3
/usr/share/man/man3/gnutls_anti_replay_deinit.3
/usr/share/man/man3/gnutls_anti_replay_enable.3
/usr/share/man/man3/gnutls_anti_replay_init.3
/usr/share/man/man3/gnutls_anti_replay_set_add_function.3
/usr/share/man/man3/gnutls_anti_replay_set_ptr.3
/usr/share/man/man3/gnutls_anti_replay_set_window.3
/usr/share/man/man3/gnutls_auth_client_get_type.3
/usr/share/man/man3/gnutls_auth_get_type.3
/usr/share/man/man3/gnutls_auth_server_get_type.3
/usr/share/man/man3/gnutls_base64_decode2.3
/usr/share/man/man3/gnutls_base64_encode2.3
/usr/share/man/man3/gnutls_buffer_append_data.3
/usr/share/man/man3/gnutls_bye.3
/usr/share/man/man3/gnutls_certificate_activation_time_peers.3
/usr/share/man/man3/gnutls_certificate_allocate_credentials.3
/usr/share/man/man3/gnutls_certificate_client_get_request_status.3
/usr/share/man/man3/gnutls_certificate_expiration_time_peers.3
/usr/share/man/man3/gnutls_certificate_free_ca_names.3
/usr/share/man/man3/gnutls_certificate_free_cas.3
/usr/share/man/man3/gnutls_certificate_free_credentials.3
/usr/share/man/man3/gnutls_certificate_free_crls.3
/usr/share/man/man3/gnutls_certificate_free_keys.3
/usr/share/man/man3/gnutls_certificate_get_crt_raw.3
/usr/share/man/man3/gnutls_certificate_get_issuer.3
/usr/share/man/man3/gnutls_certificate_get_ocsp_expiration.3
/usr/share/man/man3/gnutls_certificate_get_ours.3
/usr/share/man/man3/gnutls_certificate_get_peers.3
/usr/share/man/man3/gnutls_certificate_get_peers_subkey_id.3
/usr/share/man/man3/gnutls_certificate_get_trust_list.3
/usr/share/man/man3/gnutls_certificate_get_verify_flags.3
/usr/share/man/man3/gnutls_certificate_get_x509_crt.3
/usr/share/man/man3/gnutls_certificate_get_x509_key.3
/usr/share/man/man3/gnutls_certificate_send_x509_rdn_sequence.3
/usr/share/man/man3/gnutls_certificate_server_set_request.3
/usr/share/man/man3/gnutls_certificate_set_dh_params.3
/usr/share/man/man3/gnutls_certificate_set_flags.3
/usr/share/man/man3/gnutls_certificate_set_key.3
/usr/share/man/man3/gnutls_certificate_set_known_dh_params.3
/usr/share/man/man3/gnutls_certificate_set_ocsp_status_request_file.3
/usr/share/man/man3/gnutls_certificate_set_ocsp_status_request_file2.3
/usr/share/man/man3/gnutls_certificate_set_ocsp_status_request_function.3
/usr/share/man/man3/gnutls_certificate_set_ocsp_status_request_function2.3
/usr/share/man/man3/gnutls_certificate_set_ocsp_status_request_mem.3
/usr/share/man/man3/gnutls_certificate_set_params_function.3
/usr/share/man/man3/gnutls_certificate_set_pin_function.3
/usr/share/man/man3/gnutls_certificate_set_rawpk_key_file.3
/usr/share/man/man3/gnutls_certificate_set_rawpk_key_mem.3
/usr/share/man/man3/gnutls_certificate_set_retrieve_function.3
/usr/share/man/man3/gnutls_certificate_set_retrieve_function2.3
/usr/share/man/man3/gnutls_certificate_set_retrieve_function3.3
/usr/share/man/man3/gnutls_certificate_set_trust_list.3
/usr/share/man/man3/gnutls_certificate_set_verify_flags.3
/usr/share/man/man3/gnutls_certificate_set_verify_function.3
/usr/share/man/man3/gnutls_certificate_set_verify_limits.3
/usr/share/man/man3/gnutls_certificate_set_x509_crl.3
/usr/share/man/man3/gnutls_certificate_set_x509_crl_file.3
/usr/share/man/man3/gnutls_certificate_set_x509_crl_mem.3
/usr/share/man/man3/gnutls_certificate_set_x509_key.3
/usr/share/man/man3/gnutls_certificate_set_x509_key_file.3
/usr/share/man/man3/gnutls_certificate_set_x509_key_file2.3
/usr/share/man/man3/gnutls_certificate_set_x509_key_mem.3
/usr/share/man/man3/gnutls_certificate_set_x509_key_mem2.3
/usr/share/man/man3/gnutls_certificate_set_x509_simple_pkcs12_file.3
/usr/share/man/man3/gnutls_certificate_set_x509_simple_pkcs12_mem.3
/usr/share/man/man3/gnutls_certificate_set_x509_system_trust.3
/usr/share/man/man3/gnutls_certificate_set_x509_trust.3
/usr/share/man/man3/gnutls_certificate_set_x509_trust_dir.3
/usr/share/man/man3/gnutls_certificate_set_x509_trust_file.3
/usr/share/man/man3/gnutls_certificate_set_x509_trust_mem.3
/usr/share/man/man3/gnutls_certificate_type_get.3
/usr/share/man/man3/gnutls_certificate_type_get2.3
/usr/share/man/man3/gnutls_certificate_type_get_id.3
/usr/share/man/man3/gnutls_certificate_type_get_name.3
/usr/share/man/man3/gnutls_certificate_type_list.3
/usr/share/man/man3/gnutls_certificate_verification_profile_get_id.3
/usr/share/man/man3/gnutls_certificate_verification_profile_get_name.3
/usr/share/man/man3/gnutls_certificate_verification_status_print.3
/usr/share/man/man3/gnutls_certificate_verify_peers.3
/usr/share/man/man3/gnutls_certificate_verify_peers2.3
/usr/share/man/man3/gnutls_certificate_verify_peers3.3
/usr/share/man/man3/gnutls_check_version.3
/usr/share/man/man3/gnutls_cipher_add_auth.3
/usr/share/man/man3/gnutls_cipher_decrypt.3
/usr/share/man/man3/gnutls_cipher_decrypt2.3
/usr/share/man/man3/gnutls_cipher_deinit.3
/usr/share/man/man3/gnutls_cipher_encrypt.3
/usr/share/man/man3/gnutls_cipher_encrypt2.3
/usr/share/man/man3/gnutls_cipher_get.3
/usr/share/man/man3/gnutls_cipher_get_block_size.3
/usr/share/man/man3/gnutls_cipher_get_id.3
/usr/share/man/man3/gnutls_cipher_get_iv_size.3
/usr/share/man/man3/gnutls_cipher_get_key_size.3
/usr/share/man/man3/gnutls_cipher_get_name.3
/usr/share/man/man3/gnutls_cipher_get_tag_size.3
/usr/share/man/man3/gnutls_cipher_init.3
/usr/share/man/man3/gnutls_cipher_list.3
/usr/share/man/man3/gnutls_cipher_set_iv.3
/usr/share/man/man3/gnutls_cipher_suite_get_name.3
/usr/share/man/man3/gnutls_cipher_suite_info.3
/usr/share/man/man3/gnutls_cipher_tag.3
/usr/share/man/man3/gnutls_compression_get.3
/usr/share/man/man3/gnutls_compression_get_id.3
/usr/share/man/man3/gnutls_compression_get_name.3
/usr/share/man/man3/gnutls_compression_list.3
/usr/share/man/man3/gnutls_credentials_clear.3
/usr/share/man/man3/gnutls_credentials_get.3
/usr/share/man/man3/gnutls_credentials_set.3
/usr/share/man/man3/gnutls_crypto_register_aead_cipher.3
/usr/share/man/man3/gnutls_crypto_register_cipher.3
/usr/share/man/man3/gnutls_crypto_register_digest.3
/usr/share/man/man3/gnutls_crypto_register_mac.3
/usr/share/man/man3/gnutls_db_check_entry.3
/usr/share/man/man3/gnutls_db_check_entry_expire_time.3
/usr/share/man/man3/gnutls_db_check_entry_time.3
/usr/share/man/man3/gnutls_db_get_default_cache_expiration.3
/usr/share/man/man3/gnutls_db_get_ptr.3
/usr/share/man/man3/gnutls_db_remove_session.3
/usr/share/man/man3/gnutls_db_set_cache_expiration.3
/usr/share/man/man3/gnutls_db_set_ptr.3
/usr/share/man/man3/gnutls_db_set_remove_function.3
/usr/share/man/man3/gnutls_db_set_retrieve_function.3
/usr/share/man/man3/gnutls_db_set_store_function.3
/usr/share/man/man3/gnutls_decode_ber_digest_info.3
/usr/share/man/man3/gnutls_decode_gost_rs_value.3
/usr/share/man/man3/gnutls_decode_rs_value.3
/usr/share/man/man3/gnutls_deinit.3
/usr/share/man/man3/gnutls_dh_get_group.3
/usr/share/man/man3/gnutls_dh_get_peers_public_bits.3
/usr/share/man/man3/gnutls_dh_get_prime_bits.3
/usr/share/man/man3/gnutls_dh_get_pubkey.3
/usr/share/man/man3/gnutls_dh_get_secret_bits.3
/usr/share/man/man3/gnutls_dh_params_cpy.3
/usr/share/man/man3/gnutls_dh_params_deinit.3
/usr/share/man/man3/gnutls_dh_params_export2_pkcs3.3
/usr/share/man/man3/gnutls_dh_params_export_pkcs3.3
/usr/share/man/man3/gnutls_dh_params_export_raw.3
/usr/share/man/man3/gnutls_dh_params_generate2.3
/usr/share/man/man3/gnutls_dh_params_import_dsa.3
/usr/share/man/man3/gnutls_dh_params_import_pkcs3.3
/usr/share/man/man3/gnutls_dh_params_import_raw.3
/usr/share/man/man3/gnutls_dh_params_import_raw2.3
/usr/share/man/man3/gnutls_dh_params_import_raw3.3
/usr/share/man/man3/gnutls_dh_params_init.3
/usr/share/man/man3/gnutls_dh_set_prime_bits.3
/usr/share/man/man3/gnutls_digest_get_id.3
/usr/share/man/man3/gnutls_digest_get_name.3
/usr/share/man/man3/gnutls_digest_get_oid.3
/usr/share/man/man3/gnutls_digest_list.3
/usr/share/man/man3/gnutls_dtls_cookie_send.3
/usr/share/man/man3/gnutls_dtls_cookie_verify.3
/usr/share/man/man3/gnutls_dtls_get_data_mtu.3
/usr/share/man/man3/gnutls_dtls_get_mtu.3
/usr/share/man/man3/gnutls_dtls_get_timeout.3
/usr/share/man/man3/gnutls_dtls_prestate_set.3
/usr/share/man/man3/gnutls_dtls_set_data_mtu.3
/usr/share/man/man3/gnutls_dtls_set_mtu.3
/usr/share/man/man3/gnutls_dtls_set_timeouts.3
/usr/share/man/man3/gnutls_ecc_curve_get.3
/usr/share/man/man3/gnutls_ecc_curve_get_id.3
/usr/share/man/man3/gnutls_ecc_curve_get_name.3
/usr/share/man/man3/gnutls_ecc_curve_get_oid.3
/usr/share/man/man3/gnutls_ecc_curve_get_pk.3
/usr/share/man/man3/gnutls_ecc_curve_get_size.3
/usr/share/man/man3/gnutls_ecc_curve_list.3
/usr/share/man/man3/gnutls_encode_ber_digest_info.3
/usr/share/man/man3/gnutls_encode_gost_rs_value.3
/usr/share/man/man3/gnutls_encode_rs_value.3
/usr/share/man/man3/gnutls_error_is_fatal.3
/usr/share/man/man3/gnutls_error_to_alert.3
/usr/share/man/man3/gnutls_est_record_overhead_size.3
/usr/share/man/man3/gnutls_ext_get_current_msg.3
/usr/share/man/man3/gnutls_ext_get_data.3
/usr/share/man/man3/gnutls_ext_get_name.3
/usr/share/man/man3/gnutls_ext_get_name2.3
/usr/share/man/man3/gnutls_ext_raw_parse.3
/usr/share/man/man3/gnutls_ext_register.3
/usr/share/man/man3/gnutls_ext_set_data.3
/usr/share/man/man3/gnutls_fingerprint.3
/usr/share/man/man3/gnutls_fips140_mode_enabled.3
/usr/share/man/man3/gnutls_fips140_set_mode.3
/usr/share/man/man3/gnutls_get_system_config_file.3
/usr/share/man/man3/gnutls_global_deinit.3
/usr/share/man/man3/gnutls_global_init.3
/usr/share/man/man3/gnutls_global_set_audit_log_function.3
/usr/share/man/man3/gnutls_global_set_log_function.3
/usr/share/man/man3/gnutls_global_set_log_level.3
/usr/share/man/man3/gnutls_global_set_mem_functions.3
/usr/share/man/man3/gnutls_global_set_mutex.3
/usr/share/man/man3/gnutls_global_set_time_function.3
/usr/share/man/man3/gnutls_gost_paramset_get_name.3
/usr/share/man/man3/gnutls_gost_paramset_get_oid.3
/usr/share/man/man3/gnutls_group_get.3
/usr/share/man/man3/gnutls_group_get_id.3
/usr/share/man/man3/gnutls_group_get_name.3
/usr/share/man/man3/gnutls_group_list.3
/usr/share/man/man3/gnutls_handshake.3
/usr/share/man/man3/gnutls_handshake_description_get_name.3
/usr/share/man/man3/gnutls_handshake_get_last_in.3
/usr/share/man/man3/gnutls_handshake_get_last_out.3
/usr/share/man/man3/gnutls_handshake_set_hook_function.3
/usr/share/man/man3/gnutls_handshake_set_max_packet_length.3
/usr/share/man/man3/gnutls_handshake_set_post_client_hello_function.3
/usr/share/man/man3/gnutls_handshake_set_private_extensions.3
/usr/share/man/man3/gnutls_handshake_set_random.3
/usr/share/man/man3/gnutls_handshake_set_timeout.3
/usr/share/man/man3/gnutls_hash.3
/usr/share/man/man3/gnutls_hash_copy.3
/usr/share/man/man3/gnutls_hash_deinit.3
/usr/share/man/man3/gnutls_hash_fast.3
/usr/share/man/man3/gnutls_hash_get_len.3
/usr/share/man/man3/gnutls_hash_init.3
/usr/share/man/man3/gnutls_hash_output.3
/usr/share/man/man3/gnutls_heartbeat_allowed.3
/usr/share/man/man3/gnutls_heartbeat_enable.3
/usr/share/man/man3/gnutls_heartbeat_get_timeout.3
/usr/share/man/man3/gnutls_heartbeat_ping.3
/usr/share/man/man3/gnutls_heartbeat_pong.3
/usr/share/man/man3/gnutls_heartbeat_set_timeouts.3
/usr/share/man/man3/gnutls_hex2bin.3
/usr/share/man/man3/gnutls_hex_decode.3
/usr/share/man/man3/gnutls_hex_decode2.3
/usr/share/man/man3/gnutls_hex_encode.3
/usr/share/man/man3/gnutls_hex_encode2.3
/usr/share/man/man3/gnutls_hkdf_expand.3
/usr/share/man/man3/gnutls_hkdf_extract.3
/usr/share/man/man3/gnutls_hmac.3
/usr/share/man/man3/gnutls_hmac_copy.3
/usr/share/man/man3/gnutls_hmac_deinit.3
/usr/share/man/man3/gnutls_hmac_fast.3
/usr/share/man/man3/gnutls_hmac_get_key_size.3
/usr/share/man/man3/gnutls_hmac_get_len.3
/usr/share/man/man3/gnutls_hmac_init.3
/usr/share/man/man3/gnutls_hmac_output.3
/usr/share/man/man3/gnutls_hmac_set_nonce.3
/usr/share/man/man3/gnutls_idna_map.3
/usr/share/man/man3/gnutls_idna_reverse_map.3
/usr/share/man/man3/gnutls_init.3
/usr/share/man/man3/gnutls_key_generate.3
/usr/share/man/man3/gnutls_kx_get.3
/usr/share/man/man3/gnutls_kx_get_id.3
/usr/share/man/man3/gnutls_kx_get_name.3
/usr/share/man/man3/gnutls_kx_list.3
/usr/share/man/man3/gnutls_load_file.3
/usr/share/man/man3/gnutls_mac_get.3
/usr/share/man/man3/gnutls_mac_get_id.3
/usr/share/man/man3/gnutls_mac_get_key_size.3
/usr/share/man/man3/gnutls_mac_get_name.3
/usr/share/man/man3/gnutls_mac_get_nonce_size.3
/usr/share/man/man3/gnutls_mac_list.3
/usr/share/man/man3/gnutls_memcmp.3
/usr/share/man/man3/gnutls_memset.3
/usr/share/man/man3/gnutls_ocsp_req_add_cert.3
/usr/share/man/man3/gnutls_ocsp_req_add_cert_id.3
/usr/share/man/man3/gnutls_ocsp_req_deinit.3
/usr/share/man/man3/gnutls_ocsp_req_export.3
/usr/share/man/man3/gnutls_ocsp_req_get_cert_id.3
/usr/share/man/man3/gnutls_ocsp_req_get_extension.3
/usr/share/man/man3/gnutls_ocsp_req_get_nonce.3
/usr/share/man/man3/gnutls_ocsp_req_get_version.3
/usr/share/man/man3/gnutls_ocsp_req_import.3
/usr/share/man/man3/gnutls_ocsp_req_init.3
/usr/share/man/man3/gnutls_ocsp_req_print.3
/usr/share/man/man3/gnutls_ocsp_req_randomize_nonce.3
/usr/share/man/man3/gnutls_ocsp_req_set_extension.3
/usr/share/man/man3/gnutls_ocsp_req_set_nonce.3
/usr/share/man/man3/gnutls_ocsp_resp_check_crt.3
/usr/share/man/man3/gnutls_ocsp_resp_deinit.3
/usr/share/man/man3/gnutls_ocsp_resp_export.3
/usr/share/man/man3/gnutls_ocsp_resp_export2.3
/usr/share/man/man3/gnutls_ocsp_resp_get_certs.3
/usr/share/man/man3/gnutls_ocsp_resp_get_extension.3
/usr/share/man/man3/gnutls_ocsp_resp_get_nonce.3
/usr/share/man/man3/gnutls_ocsp_resp_get_produced.3
/usr/share/man/man3/gnutls_ocsp_resp_get_responder.3
/usr/share/man/man3/gnutls_ocsp_resp_get_responder2.3
/usr/share/man/man3/gnutls_ocsp_resp_get_responder_raw_id.3
/usr/share/man/man3/gnutls_ocsp_resp_get_response.3
/usr/share/man/man3/gnutls_ocsp_resp_get_signature.3
/usr/share/man/man3/gnutls_ocsp_resp_get_signature_algorithm.3
/usr/share/man/man3/gnutls_ocsp_resp_get_single.3
/usr/share/man/man3/gnutls_ocsp_resp_get_status.3
/usr/share/man/man3/gnutls_ocsp_resp_get_version.3
/usr/share/man/man3/gnutls_ocsp_resp_import.3
/usr/share/man/man3/gnutls_ocsp_resp_import2.3
/usr/share/man/man3/gnutls_ocsp_resp_init.3
/usr/share/man/man3/gnutls_ocsp_resp_list_import2.3
/usr/share/man/man3/gnutls_ocsp_resp_print.3
/usr/share/man/man3/gnutls_ocsp_resp_verify.3
/usr/share/man/man3/gnutls_ocsp_resp_verify_direct.3
/usr/share/man/man3/gnutls_ocsp_status_request_enable_client.3
/usr/share/man/man3/gnutls_ocsp_status_request_get.3
/usr/share/man/man3/gnutls_ocsp_status_request_get2.3
/usr/share/man/man3/gnutls_ocsp_status_request_is_checked.3
/usr/share/man/man3/gnutls_oid_to_digest.3
/usr/share/man/man3/gnutls_oid_to_ecc_curve.3
/usr/share/man/man3/gnutls_oid_to_gost_paramset.3
/usr/share/man/man3/gnutls_oid_to_mac.3
/usr/share/man/man3/gnutls_oid_to_pk.3
/usr/share/man/man3/gnutls_oid_to_sign.3
/usr/share/man/man3/gnutls_openpgp_privkey_sign_hash.3
/usr/share/man/man3/gnutls_openpgp_send_cert.3
/usr/share/man/man3/gnutls_packet_deinit.3
/usr/share/man/man3/gnutls_packet_get.3
/usr/share/man/man3/gnutls_pbkdf2.3
/usr/share/man/man3/gnutls_pcert_deinit.3
/usr/share/man/man3/gnutls_pcert_export_openpgp.3
/usr/share/man/man3/gnutls_pcert_export_x509.3
/usr/share/man/man3/gnutls_pcert_import_openpgp.3
/usr/share/man/man3/gnutls_pcert_import_openpgp_raw.3
/usr/share/man/man3/gnutls_pcert_import_rawpk.3
/usr/share/man/man3/gnutls_pcert_import_rawpk_raw.3
/usr/share/man/man3/gnutls_pcert_import_x509.3
/usr/share/man/man3/gnutls_pcert_import_x509_list.3
/usr/share/man/man3/gnutls_pcert_import_x509_raw.3
/usr/share/man/man3/gnutls_pcert_list_import_x509_file.3
/usr/share/man/man3/gnutls_pcert_list_import_x509_raw.3
/usr/share/man/man3/gnutls_pem_base64_decode.3
/usr/share/man/man3/gnutls_pem_base64_decode2.3
/usr/share/man/man3/gnutls_pem_base64_encode.3
/usr/share/man/man3/gnutls_pem_base64_encode2.3
/usr/share/man/man3/gnutls_perror.3
/usr/share/man/man3/gnutls_pk_algorithm_get_name.3
/usr/share/man/man3/gnutls_pk_bits_to_sec_param.3
/usr/share/man/man3/gnutls_pk_get_id.3
/usr/share/man/man3/gnutls_pk_get_name.3
/usr/share/man/man3/gnutls_pk_get_oid.3
/usr/share/man/man3/gnutls_pk_list.3
/usr/share/man/man3/gnutls_pk_to_sign.3
/usr/share/man/man3/gnutls_pkcs11_add_provider.3
/usr/share/man/man3/gnutls_pkcs11_copy_attached_extension.3
/usr/share/man/man3/gnutls_pkcs11_copy_pubkey.3
/usr/share/man/man3/gnutls_pkcs11_copy_secret_key.3
/usr/share/man/man3/gnutls_pkcs11_copy_x509_crt.3
/usr/share/man/man3/gnutls_pkcs11_copy_x509_crt2.3
/usr/share/man/man3/gnutls_pkcs11_copy_x509_privkey.3
/usr/share/man/man3/gnutls_pkcs11_copy_x509_privkey2.3
/usr/share/man/man3/gnutls_pkcs11_crt_is_known.3
/usr/share/man/man3/gnutls_pkcs11_deinit.3
/usr/share/man/man3/gnutls_pkcs11_delete_url.3
/usr/share/man/man3/gnutls_pkcs11_get_pin_function.3
/usr/share/man/man3/gnutls_pkcs11_get_raw_issuer.3
/usr/share/man/man3/gnutls_pkcs11_get_raw_issuer_by_dn.3
/usr/share/man/man3/gnutls_pkcs11_get_raw_issuer_by_subject_key_id.3
/usr/share/man/man3/gnutls_pkcs11_init.3
/usr/share/man/man3/gnutls_pkcs11_obj_deinit.3
/usr/share/man/man3/gnutls_pkcs11_obj_export.3
/usr/share/man/man3/gnutls_pkcs11_obj_export2.3
/usr/share/man/man3/gnutls_pkcs11_obj_export3.3
/usr/share/man/man3/gnutls_pkcs11_obj_export_url.3
/usr/share/man/man3/gnutls_pkcs11_obj_flags_get_str.3
/usr/share/man/man3/gnutls_pkcs11_obj_get_exts.3
/usr/share/man/man3/gnutls_pkcs11_obj_get_flags.3
/usr/share/man/man3/gnutls_pkcs11_obj_get_info.3
/usr/share/man/man3/gnutls_pkcs11_obj_get_ptr.3
/usr/share/man/man3/gnutls_pkcs11_obj_get_type.3
/usr/share/man/man3/gnutls_pkcs11_obj_import_url.3
/usr/share/man/man3/gnutls_pkcs11_obj_init.3
/usr/share/man/man3/gnutls_pkcs11_obj_list_import_url3.3
/usr/share/man/man3/gnutls_pkcs11_obj_list_import_url4.3
/usr/share/man/man3/gnutls_pkcs11_obj_set_info.3
/usr/share/man/man3/gnutls_pkcs11_obj_set_pin_function.3
/usr/share/man/man3/gnutls_pkcs11_privkey_cpy.3
/usr/share/man/man3/gnutls_pkcs11_privkey_deinit.3
/usr/share/man/man3/gnutls_pkcs11_privkey_export_pubkey.3
/usr/share/man/man3/gnutls_pkcs11_privkey_export_url.3
/usr/share/man/man3/gnutls_pkcs11_privkey_generate.3
/usr/share/man/man3/gnutls_pkcs11_privkey_generate2.3
/usr/share/man/man3/gnutls_pkcs11_privkey_generate3.3
/usr/share/man/man3/gnutls_pkcs11_privkey_get_info.3
/usr/share/man/man3/gnutls_pkcs11_privkey_get_pk_algorithm.3
/usr/share/man/man3/gnutls_pkcs11_privkey_import_url.3
/usr/share/man/man3/gnutls_pkcs11_privkey_init.3
/usr/share/man/man3/gnutls_pkcs11_privkey_set_pin_function.3
/usr/share/man/man3/gnutls_pkcs11_privkey_status.3
/usr/share/man/man3/gnutls_pkcs11_reinit.3
/usr/share/man/man3/gnutls_pkcs11_set_pin_function.3
/usr/share/man/man3/gnutls_pkcs11_set_token_function.3
/usr/share/man/man3/gnutls_pkcs11_token_check_mechanism.3
/usr/share/man/man3/gnutls_pkcs11_token_get_flags.3
/usr/share/man/man3/gnutls_pkcs11_token_get_info.3
/usr/share/man/man3/gnutls_pkcs11_token_get_mechanism.3
/usr/share/man/man3/gnutls_pkcs11_token_get_ptr.3
/usr/share/man/man3/gnutls_pkcs11_token_get_random.3
/usr/share/man/man3/gnutls_pkcs11_token_get_url.3
/usr/share/man/man3/gnutls_pkcs11_token_init.3
/usr/share/man/man3/gnutls_pkcs11_token_set_pin.3
/usr/share/man/man3/gnutls_pkcs11_type_get_name.3
/usr/share/man/man3/gnutls_pkcs12_bag_decrypt.3
/usr/share/man/man3/gnutls_pkcs12_bag_deinit.3
/usr/share/man/man3/gnutls_pkcs12_bag_enc_info.3
/usr/share/man/man3/gnutls_pkcs12_bag_encrypt.3
/usr/share/man/man3/gnutls_pkcs12_bag_get_count.3
/usr/share/man/man3/gnutls_pkcs12_bag_get_data.3
/usr/share/man/man3/gnutls_pkcs12_bag_get_friendly_name.3
/usr/share/man/man3/gnutls_pkcs12_bag_get_key_id.3
/usr/share/man/man3/gnutls_pkcs12_bag_get_type.3
/usr/share/man/man3/gnutls_pkcs12_bag_init.3
/usr/share/man/man3/gnutls_pkcs12_bag_set_crl.3
/usr/share/man/man3/gnutls_pkcs12_bag_set_crt.3
/usr/share/man/man3/gnutls_pkcs12_bag_set_data.3
/usr/share/man/man3/gnutls_pkcs12_bag_set_friendly_name.3
/usr/share/man/man3/gnutls_pkcs12_bag_set_key_id.3
/usr/share/man/man3/gnutls_pkcs12_bag_set_privkey.3
/usr/share/man/man3/gnutls_pkcs12_deinit.3
/usr/share/man/man3/gnutls_pkcs12_export.3
/usr/share/man/man3/gnutls_pkcs12_export2.3
/usr/share/man/man3/gnutls_pkcs12_generate_mac.3
/usr/share/man/man3/gnutls_pkcs12_generate_mac2.3
/usr/share/man/man3/gnutls_pkcs12_get_bag.3
/usr/share/man/man3/gnutls_pkcs12_import.3
/usr/share/man/man3/gnutls_pkcs12_init.3
/usr/share/man/man3/gnutls_pkcs12_mac_info.3
/usr/share/man/man3/gnutls_pkcs12_set_bag.3
/usr/share/man/man3/gnutls_pkcs12_simple_parse.3
/usr/share/man/man3/gnutls_pkcs12_verify_mac.3
/usr/share/man/man3/gnutls_pkcs7_add_attr.3
/usr/share/man/man3/gnutls_pkcs7_attrs_deinit.3
/usr/share/man/man3/gnutls_pkcs7_deinit.3
/usr/share/man/man3/gnutls_pkcs7_delete_crl.3
/usr/share/man/man3/gnutls_pkcs7_delete_crt.3
/usr/share/man/man3/gnutls_pkcs7_export.3
/usr/share/man/man3/gnutls_pkcs7_export2.3
/usr/share/man/man3/gnutls_pkcs7_get_attr.3
/usr/share/man/man3/gnutls_pkcs7_get_crl_count.3
/usr/share/man/man3/gnutls_pkcs7_get_crl_raw.3
/usr/share/man/man3/gnutls_pkcs7_get_crl_raw2.3
/usr/share/man/man3/gnutls_pkcs7_get_crt_count.3
/usr/share/man/man3/gnutls_pkcs7_get_crt_raw.3
/usr/share/man/man3/gnutls_pkcs7_get_crt_raw2.3
/usr/share/man/man3/gnutls_pkcs7_get_embedded_data.3
/usr/share/man/man3/gnutls_pkcs7_get_embedded_data_oid.3
/usr/share/man/man3/gnutls_pkcs7_get_signature_count.3
/usr/share/man/man3/gnutls_pkcs7_get_signature_info.3
/usr/share/man/man3/gnutls_pkcs7_import.3
/usr/share/man/man3/gnutls_pkcs7_init.3
/usr/share/man/man3/gnutls_pkcs7_print.3
/usr/share/man/man3/gnutls_pkcs7_print_signature_info.3
/usr/share/man/man3/gnutls_pkcs7_set_crl.3
/usr/share/man/man3/gnutls_pkcs7_set_crl_raw.3
/usr/share/man/man3/gnutls_pkcs7_set_crt.3
/usr/share/man/man3/gnutls_pkcs7_set_crt_raw.3
/usr/share/man/man3/gnutls_pkcs7_sign.3
/usr/share/man/man3/gnutls_pkcs7_signature_info_deinit.3
/usr/share/man/man3/gnutls_pkcs7_verify.3
/usr/share/man/man3/gnutls_pkcs7_verify_direct.3
/usr/share/man/man3/gnutls_pkcs8_info.3
/usr/share/man/man3/gnutls_pkcs_schema_get_name.3
/usr/share/man/man3/gnutls_pkcs_schema_get_oid.3
/usr/share/man/man3/gnutls_prf.3
/usr/share/man/man3/gnutls_prf_early.3
/usr/share/man/man3/gnutls_prf_hash_get.3
/usr/share/man/man3/gnutls_prf_raw.3
/usr/share/man/man3/gnutls_prf_rfc5705.3
/usr/share/man/man3/gnutls_priority_certificate_type_list.3
/usr/share/man/man3/gnutls_priority_certificate_type_list2.3
/usr/share/man/man3/gnutls_priority_cipher_list.3
/usr/share/man/man3/gnutls_priority_compression_list.3
/usr/share/man/man3/gnutls_priority_deinit.3
/usr/share/man/man3/gnutls_priority_ecc_curve_list.3
/usr/share/man/man3/gnutls_priority_get_cipher_suite_index.3
/usr/share/man/man3/gnutls_priority_group_list.3
/usr/share/man/man3/gnutls_priority_init.3
/usr/share/man/man3/gnutls_priority_init2.3
/usr/share/man/man3/gnutls_priority_kx_list.3
/usr/share/man/man3/gnutls_priority_mac_list.3
/usr/share/man/man3/gnutls_priority_protocol_list.3
/usr/share/man/man3/gnutls_priority_set.3
/usr/share/man/man3/gnutls_priority_set_direct.3
/usr/share/man/man3/gnutls_priority_sign_list.3
/usr/share/man/man3/gnutls_priority_string_list.3
/usr/share/man/man3/gnutls_privkey_decrypt_data.3
/usr/share/man/man3/gnutls_privkey_decrypt_data2.3
/usr/share/man/man3/gnutls_privkey_deinit.3
/usr/share/man/man3/gnutls_privkey_export_dsa_raw.3
/usr/share/man/man3/gnutls_privkey_export_dsa_raw2.3
/usr/share/man/man3/gnutls_privkey_export_ecc_raw.3
/usr/share/man/man3/gnutls_privkey_export_ecc_raw2.3
/usr/share/man/man3/gnutls_privkey_export_gost_raw2.3
/usr/share/man/man3/gnutls_privkey_export_openpgp.3
/usr/share/man/man3/gnutls_privkey_export_pkcs11.3
/usr/share/man/man3/gnutls_privkey_export_rsa_raw.3
/usr/share/man/man3/gnutls_privkey_export_rsa_raw2.3
/usr/share/man/man3/gnutls_privkey_export_x509.3
/usr/share/man/man3/gnutls_privkey_generate.3
/usr/share/man/man3/gnutls_privkey_generate2.3
/usr/share/man/man3/gnutls_privkey_get_pk_algorithm.3
/usr/share/man/man3/gnutls_privkey_get_seed.3
/usr/share/man/man3/gnutls_privkey_get_spki.3
/usr/share/man/man3/gnutls_privkey_get_type.3
/usr/share/man/man3/gnutls_privkey_import_dsa_raw.3
/usr/share/man/man3/gnutls_privkey_import_ecc_raw.3
/usr/share/man/man3/gnutls_privkey_import_ext.3
/usr/share/man/man3/gnutls_privkey_import_ext2.3
/usr/share/man/man3/gnutls_privkey_import_ext3.3
/usr/share/man/man3/gnutls_privkey_import_ext4.3
/usr/share/man/man3/gnutls_privkey_import_gost_raw.3
/usr/share/man/man3/gnutls_privkey_import_openpgp.3
/usr/share/man/man3/gnutls_privkey_import_openpgp_raw.3
/usr/share/man/man3/gnutls_privkey_import_pkcs11.3
/usr/share/man/man3/gnutls_privkey_import_pkcs11_url.3
/usr/share/man/man3/gnutls_privkey_import_rsa_raw.3
/usr/share/man/man3/gnutls_privkey_import_tpm_raw.3
/usr/share/man/man3/gnutls_privkey_import_tpm_url.3
/usr/share/man/man3/gnutls_privkey_import_url.3
/usr/share/man/man3/gnutls_privkey_import_x509.3
/usr/share/man/man3/gnutls_privkey_import_x509_raw.3
/usr/share/man/man3/gnutls_privkey_init.3
/usr/share/man/man3/gnutls_privkey_set_flags.3
/usr/share/man/man3/gnutls_privkey_set_pin_function.3
/usr/share/man/man3/gnutls_privkey_set_spki.3
/usr/share/man/man3/gnutls_privkey_sign_data.3
/usr/share/man/man3/gnutls_privkey_sign_data2.3
/usr/share/man/man3/gnutls_privkey_sign_hash.3
/usr/share/man/man3/gnutls_privkey_sign_hash2.3
/usr/share/man/man3/gnutls_privkey_status.3
/usr/share/man/man3/gnutls_privkey_verify_params.3
/usr/share/man/man3/gnutls_privkey_verify_seed.3
/usr/share/man/man3/gnutls_protocol_get_id.3
/usr/share/man/man3/gnutls_protocol_get_name.3
/usr/share/man/man3/gnutls_protocol_get_version.3
/usr/share/man/man3/gnutls_protocol_list.3
/usr/share/man/man3/gnutls_psk_allocate_client_credentials.3
/usr/share/man/man3/gnutls_psk_allocate_server_credentials.3
/usr/share/man/man3/gnutls_psk_client_get_hint.3
/usr/share/man/man3/gnutls_psk_free_client_credentials.3
/usr/share/man/man3/gnutls_psk_free_server_credentials.3
/usr/share/man/man3/gnutls_psk_server_get_username.3
/usr/share/man/man3/gnutls_psk_server_get_username2.3
/usr/share/man/man3/gnutls_psk_set_client_credentials.3
/usr/share/man/man3/gnutls_psk_set_client_credentials2.3
/usr/share/man/man3/gnutls_psk_set_client_credentials_function.3
/usr/share/man/man3/gnutls_psk_set_client_credentials_function2.3
/usr/share/man/man3/gnutls_psk_set_params_function.3
/usr/share/man/man3/gnutls_psk_set_server_credentials_file.3
/usr/share/man/man3/gnutls_psk_set_server_credentials_function.3
/usr/share/man/man3/gnutls_psk_set_server_credentials_function2.3
/usr/share/man/man3/gnutls_psk_set_server_credentials_hint.3
/usr/share/man/man3/gnutls_psk_set_server_dh_params.3
/usr/share/man/man3/gnutls_psk_set_server_known_dh_params.3
/usr/share/man/man3/gnutls_psk_set_server_params_function.3
/usr/share/man/man3/gnutls_pubkey_deinit.3
/usr/share/man/man3/gnutls_pubkey_encrypt_data.3
/usr/share/man/man3/gnutls_pubkey_export.3
/usr/share/man/man3/gnutls_pubkey_export2.3
/usr/share/man/man3/gnutls_pubkey_export_dsa_raw.3
/usr/share/man/man3/gnutls_pubkey_export_dsa_raw2.3
/usr/share/man/man3/gnutls_pubkey_export_ecc_raw.3
/usr/share/man/man3/gnutls_pubkey_export_ecc_raw2.3
/usr/share/man/man3/gnutls_pubkey_export_ecc_x962.3
/usr/share/man/man3/gnutls_pubkey_export_gost_raw2.3
/usr/share/man/man3/gnutls_pubkey_export_rsa_raw.3
/usr/share/man/man3/gnutls_pubkey_export_rsa_raw2.3
/usr/share/man/man3/gnutls_pubkey_get_key_id.3
/usr/share/man/man3/gnutls_pubkey_get_key_usage.3
/usr/share/man/man3/gnutls_pubkey_get_openpgp_key_id.3
/usr/share/man/man3/gnutls_pubkey_get_pk_algorithm.3
/usr/share/man/man3/gnutls_pubkey_get_preferred_hash_algorithm.3
/usr/share/man/man3/gnutls_pubkey_get_spki.3
/usr/share/man/man3/gnutls_pubkey_import.3
/usr/share/man/man3/gnutls_pubkey_import_dsa_raw.3
/usr/share/man/man3/gnutls_pubkey_import_ecc_raw.3
/usr/share/man/man3/gnutls_pubkey_import_ecc_x962.3
/usr/share/man/man3/gnutls_pubkey_import_gost_raw.3
/usr/share/man/man3/gnutls_pubkey_import_openpgp.3
/usr/share/man/man3/gnutls_pubkey_import_openpgp_raw.3
/usr/share/man/man3/gnutls_pubkey_import_pkcs11.3
/usr/share/man/man3/gnutls_pubkey_import_privkey.3
/usr/share/man/man3/gnutls_pubkey_import_rsa_raw.3
/usr/share/man/man3/gnutls_pubkey_import_tpm_raw.3
/usr/share/man/man3/gnutls_pubkey_import_tpm_url.3
/usr/share/man/man3/gnutls_pubkey_import_url.3
/usr/share/man/man3/gnutls_pubkey_import_x509.3
/usr/share/man/man3/gnutls_pubkey_import_x509_crq.3
/usr/share/man/man3/gnutls_pubkey_import_x509_raw.3
/usr/share/man/man3/gnutls_pubkey_init.3
/usr/share/man/man3/gnutls_pubkey_print.3
/usr/share/man/man3/gnutls_pubkey_set_key_usage.3
/usr/share/man/man3/gnutls_pubkey_set_pin_function.3
/usr/share/man/man3/gnutls_pubkey_set_spki.3
/usr/share/man/man3/gnutls_pubkey_verify_data2.3
/usr/share/man/man3/gnutls_pubkey_verify_hash2.3
/usr/share/man/man3/gnutls_pubkey_verify_params.3
/usr/share/man/man3/gnutls_random_art.3
/usr/share/man/man3/gnutls_range_split.3
/usr/share/man/man3/gnutls_reauth.3
/usr/share/man/man3/gnutls_record_can_use_length_hiding.3
/usr/share/man/man3/gnutls_record_check_corked.3
/usr/share/man/man3/gnutls_record_check_pending.3
/usr/share/man/man3/gnutls_record_cork.3
/usr/share/man/man3/gnutls_record_disable_padding.3
/usr/share/man/man3/gnutls_record_discard_queued.3
/usr/share/man/man3/gnutls_record_get_direction.3
/usr/share/man/man3/gnutls_record_get_discarded.3
/usr/share/man/man3/gnutls_record_get_max_early_data_size.3
/usr/share/man/man3/gnutls_record_get_max_size.3
/usr/share/man/man3/gnutls_record_get_state.3
/usr/share/man/man3/gnutls_record_overhead_size.3
/usr/share/man/man3/gnutls_record_recv.3
/usr/share/man/man3/gnutls_record_recv_early_data.3
/usr/share/man/man3/gnutls_record_recv_packet.3
/usr/share/man/man3/gnutls_record_recv_seq.3
/usr/share/man/man3/gnutls_record_send.3
/usr/share/man/man3/gnutls_record_send2.3
/usr/share/man/man3/gnutls_record_send_early_data.3
/usr/share/man/man3/gnutls_record_send_range.3
/usr/share/man/man3/gnutls_record_set_max_early_data_size.3
/usr/share/man/man3/gnutls_record_set_max_recv_size.3
/usr/share/man/man3/gnutls_record_set_max_size.3
/usr/share/man/man3/gnutls_record_set_state.3
/usr/share/man/man3/gnutls_record_set_timeout.3
/usr/share/man/man3/gnutls_record_uncork.3
/usr/share/man/man3/gnutls_register_custom_url.3
/usr/share/man/man3/gnutls_rehandshake.3
/usr/share/man/man3/gnutls_rnd.3
/usr/share/man/man3/gnutls_rnd_refresh.3
/usr/share/man/man3/gnutls_safe_renegotiation_status.3
/usr/share/man/man3/gnutls_sec_param_get_name.3
/usr/share/man/man3/gnutls_sec_param_to_pk_bits.3
/usr/share/man/man3/gnutls_sec_param_to_symmetric_bits.3
/usr/share/man/man3/gnutls_server_name_get.3
/usr/share/man/man3/gnutls_server_name_set.3
/usr/share/man/man3/gnutls_session_channel_binding.3
/usr/share/man/man3/gnutls_session_enable_compatibility_mode.3
/usr/share/man/man3/gnutls_session_etm_status.3
/usr/share/man/man3/gnutls_session_ext_master_secret_status.3
/usr/share/man/man3/gnutls_session_ext_register.3
/usr/share/man/man3/gnutls_session_force_valid.3
/usr/share/man/man3/gnutls_session_get_data.3
/usr/share/man/man3/gnutls_session_get_data2.3
/usr/share/man/man3/gnutls_session_get_desc.3
/usr/share/man/man3/gnutls_session_get_flags.3
/usr/share/man/man3/gnutls_session_get_id.3
/usr/share/man/man3/gnutls_session_get_id2.3
/usr/share/man/man3/gnutls_session_get_keylog_function.3
/usr/share/man/man3/gnutls_session_get_master_secret.3
/usr/share/man/man3/gnutls_session_get_ptr.3
/usr/share/man/man3/gnutls_session_get_random.3
/usr/share/man/man3/gnutls_session_get_verify_cert_status.3
/usr/share/man/man3/gnutls_session_is_resumed.3
/usr/share/man/man3/gnutls_session_key_update.3
/usr/share/man/man3/gnutls_session_resumption_requested.3
/usr/share/man/man3/gnutls_session_set_data.3
/usr/share/man/man3/gnutls_session_set_id.3
/usr/share/man/man3/gnutls_session_set_keylog_function.3
/usr/share/man/man3/gnutls_session_set_premaster.3
/usr/share/man/man3/gnutls_session_set_ptr.3
/usr/share/man/man3/gnutls_session_set_verify_cert.3
/usr/share/man/man3/gnutls_session_set_verify_cert2.3
/usr/share/man/man3/gnutls_session_set_verify_function.3
/usr/share/man/man3/gnutls_session_supplemental_register.3
/usr/share/man/man3/gnutls_session_ticket_enable_client.3
/usr/share/man/man3/gnutls_session_ticket_enable_server.3
/usr/share/man/man3/gnutls_session_ticket_key_generate.3
/usr/share/man/man3/gnutls_session_ticket_send.3
/usr/share/man/man3/gnutls_set_default_priority.3
/usr/share/man/man3/gnutls_set_default_priority_append.3
/usr/share/man/man3/gnutls_sign_algorithm_get.3
/usr/share/man/man3/gnutls_sign_algorithm_get_client.3
/usr/share/man/man3/gnutls_sign_algorithm_get_requested.3
/usr/share/man/man3/gnutls_sign_get_hash_algorithm.3
/usr/share/man/man3/gnutls_sign_get_id.3
/usr/share/man/man3/gnutls_sign_get_name.3
/usr/share/man/man3/gnutls_sign_get_oid.3
/usr/share/man/man3/gnutls_sign_get_pk_algorithm.3
/usr/share/man/man3/gnutls_sign_is_secure.3
/usr/share/man/man3/gnutls_sign_is_secure2.3
/usr/share/man/man3/gnutls_sign_list.3
/usr/share/man/man3/gnutls_sign_supports_pk_algorithm.3
/usr/share/man/man3/gnutls_srp_allocate_client_credentials.3
/usr/share/man/man3/gnutls_srp_allocate_server_credentials.3
/usr/share/man/man3/gnutls_srp_base64_decode.3
/usr/share/man/man3/gnutls_srp_base64_decode2.3
/usr/share/man/man3/gnutls_srp_base64_encode.3
/usr/share/man/man3/gnutls_srp_base64_encode2.3
/usr/share/man/man3/gnutls_srp_free_client_credentials.3
/usr/share/man/man3/gnutls_srp_free_server_credentials.3
/usr/share/man/man3/gnutls_srp_server_get_username.3
/usr/share/man/man3/gnutls_srp_set_client_credentials.3
/usr/share/man/man3/gnutls_srp_set_client_credentials_function.3
/usr/share/man/man3/gnutls_srp_set_prime_bits.3
/usr/share/man/man3/gnutls_srp_set_server_credentials_file.3
/usr/share/man/man3/gnutls_srp_set_server_credentials_function.3
/usr/share/man/man3/gnutls_srp_set_server_fake_salt_seed.3
/usr/share/man/man3/gnutls_srp_verifier.3
/usr/share/man/man3/gnutls_srtp_get_keys.3
/usr/share/man/man3/gnutls_srtp_get_mki.3
/usr/share/man/man3/gnutls_srtp_get_profile_id.3
/usr/share/man/man3/gnutls_srtp_get_profile_name.3
/usr/share/man/man3/gnutls_srtp_get_selected_profile.3
/usr/share/man/man3/gnutls_srtp_set_mki.3
/usr/share/man/man3/gnutls_srtp_set_profile.3
/usr/share/man/man3/gnutls_srtp_set_profile_direct.3
/usr/share/man/man3/gnutls_store_commitment.3
/usr/share/man/man3/gnutls_store_pubkey.3
/usr/share/man/man3/gnutls_strerror.3
/usr/share/man/man3/gnutls_strerror_name.3
/usr/share/man/man3/gnutls_subject_alt_names_deinit.3
/usr/share/man/man3/gnutls_subject_alt_names_get.3
/usr/share/man/man3/gnutls_subject_alt_names_init.3
/usr/share/man/man3/gnutls_subject_alt_names_set.3
/usr/share/man/man3/gnutls_supplemental_get_name.3
/usr/share/man/man3/gnutls_supplemental_recv.3
/usr/share/man/man3/gnutls_supplemental_register.3
/usr/share/man/man3/gnutls_supplemental_send.3
/usr/share/man/man3/gnutls_system_key_add_x509.3
/usr/share/man/man3/gnutls_system_key_delete.3
/usr/share/man/man3/gnutls_system_key_iter_deinit.3
/usr/share/man/man3/gnutls_system_key_iter_get_info.3
/usr/share/man/man3/gnutls_system_recv_timeout.3
/usr/share/man/man3/gnutls_tdb_deinit.3
/usr/share/man/man3/gnutls_tdb_init.3
/usr/share/man/man3/gnutls_tdb_set_store_commitment_func.3
/usr/share/man/man3/gnutls_tdb_set_store_func.3
/usr/share/man/man3/gnutls_tdb_set_verify_func.3
/usr/share/man/man3/gnutls_tpm_get_registered.3
/usr/share/man/man3/gnutls_tpm_key_list_deinit.3
/usr/share/man/man3/gnutls_tpm_key_list_get_url.3
/usr/share/man/man3/gnutls_tpm_privkey_delete.3
/usr/share/man/man3/gnutls_tpm_privkey_generate.3
/usr/share/man/man3/gnutls_transport_get_int.3
/usr/share/man/man3/gnutls_transport_get_int2.3
/usr/share/man/man3/gnutls_transport_get_ptr.3
/usr/share/man/man3/gnutls_transport_get_ptr2.3
/usr/share/man/man3/gnutls_transport_set_errno.3
/usr/share/man/man3/gnutls_transport_set_errno_function.3
/usr/share/man/man3/gnutls_transport_set_fastopen.3
/usr/share/man/man3/gnutls_transport_set_int.3
/usr/share/man/man3/gnutls_transport_set_int2.3
/usr/share/man/man3/gnutls_transport_set_ptr.3
/usr/share/man/man3/gnutls_transport_set_ptr2.3
/usr/share/man/man3/gnutls_transport_set_pull_function.3
/usr/share/man/man3/gnutls_transport_set_pull_timeout_function.3
/usr/share/man/man3/gnutls_transport_set_push_function.3
/usr/share/man/man3/gnutls_transport_set_vec_push_function.3
/usr/share/man/man3/gnutls_url_is_supported.3
/usr/share/man/man3/gnutls_utf8_password_normalize.3
/usr/share/man/man3/gnutls_verify_stored_pubkey.3
/usr/share/man/man3/gnutls_x509_aia_deinit.3
/usr/share/man/man3/gnutls_x509_aia_get.3
/usr/share/man/man3/gnutls_x509_aia_init.3
/usr/share/man/man3/gnutls_x509_aia_set.3
/usr/share/man/man3/gnutls_x509_aki_deinit.3
/usr/share/man/man3/gnutls_x509_aki_get_cert_issuer.3
/usr/share/man/man3/gnutls_x509_aki_get_id.3
/usr/share/man/man3/gnutls_x509_aki_init.3
/usr/share/man/man3/gnutls_x509_aki_set_cert_issuer.3
/usr/share/man/man3/gnutls_x509_aki_set_id.3
/usr/share/man/man3/gnutls_x509_cidr_to_rfc5280.3
/usr/share/man/man3/gnutls_x509_crl_check_issuer.3
/usr/share/man/man3/gnutls_x509_crl_deinit.3
/usr/share/man/man3/gnutls_x509_crl_dist_points_deinit.3
/usr/share/man/man3/gnutls_x509_crl_dist_points_get.3
/usr/share/man/man3/gnutls_x509_crl_dist_points_init.3
/usr/share/man/man3/gnutls_x509_crl_dist_points_set.3
/usr/share/man/man3/gnutls_x509_crl_export.3
/usr/share/man/man3/gnutls_x509_crl_export2.3
/usr/share/man/man3/gnutls_x509_crl_get_authority_key_gn_serial.3
/usr/share/man/man3/gnutls_x509_crl_get_authority_key_id.3
/usr/share/man/man3/gnutls_x509_crl_get_crt_count.3
/usr/share/man/man3/gnutls_x509_crl_get_crt_serial.3
/usr/share/man/man3/gnutls_x509_crl_get_dn_oid.3
/usr/share/man/man3/gnutls_x509_crl_get_extension_data.3
/usr/share/man/man3/gnutls_x509_crl_get_extension_data2.3
/usr/share/man/man3/gnutls_x509_crl_get_extension_info.3
/usr/share/man/man3/gnutls_x509_crl_get_extension_oid.3
/usr/share/man/man3/gnutls_x509_crl_get_issuer_dn.3
/usr/share/man/man3/gnutls_x509_crl_get_issuer_dn2.3
/usr/share/man/man3/gnutls_x509_crl_get_issuer_dn3.3
/usr/share/man/man3/gnutls_x509_crl_get_issuer_dn_by_oid.3
/usr/share/man/man3/gnutls_x509_crl_get_next_update.3
/usr/share/man/man3/gnutls_x509_crl_get_number.3
/usr/share/man/man3/gnutls_x509_crl_get_raw_issuer_dn.3
/usr/share/man/man3/gnutls_x509_crl_get_signature.3
/usr/share/man/man3/gnutls_x509_crl_get_signature_algorithm.3
/usr/share/man/man3/gnutls_x509_crl_get_signature_oid.3
/usr/share/man/man3/gnutls_x509_crl_get_this_update.3
/usr/share/man/man3/gnutls_x509_crl_get_version.3
/usr/share/man/man3/gnutls_x509_crl_import.3
/usr/share/man/man3/gnutls_x509_crl_init.3
/usr/share/man/man3/gnutls_x509_crl_iter_crt_serial.3
/usr/share/man/man3/gnutls_x509_crl_iter_deinit.3
/usr/share/man/man3/gnutls_x509_crl_list_import.3
/usr/share/man/man3/gnutls_x509_crl_list_import2.3
/usr/share/man/man3/gnutls_x509_crl_print.3
/usr/share/man/man3/gnutls_x509_crl_privkey_sign.3
/usr/share/man/man3/gnutls_x509_crl_set_authority_key_id.3
/usr/share/man/man3/gnutls_x509_crl_set_crt.3
/usr/share/man/man3/gnutls_x509_crl_set_crt_serial.3
/usr/share/man/man3/gnutls_x509_crl_set_next_update.3
/usr/share/man/man3/gnutls_x509_crl_set_number.3
/usr/share/man/man3/gnutls_x509_crl_set_this_update.3
/usr/share/man/man3/gnutls_x509_crl_set_version.3
/usr/share/man/man3/gnutls_x509_crl_sign.3
/usr/share/man/man3/gnutls_x509_crl_sign2.3
/usr/share/man/man3/gnutls_x509_crl_verify.3
/usr/share/man/man3/gnutls_x509_crq_deinit.3
/usr/share/man/man3/gnutls_x509_crq_export.3
/usr/share/man/man3/gnutls_x509_crq_export2.3
/usr/share/man/man3/gnutls_x509_crq_get_attribute_by_oid.3
/usr/share/man/man3/gnutls_x509_crq_get_attribute_data.3
/usr/share/man/man3/gnutls_x509_crq_get_attribute_info.3
/usr/share/man/man3/gnutls_x509_crq_get_basic_constraints.3
/usr/share/man/man3/gnutls_x509_crq_get_challenge_password.3
/usr/share/man/man3/gnutls_x509_crq_get_dn.3
/usr/share/man/man3/gnutls_x509_crq_get_dn2.3
/usr/share/man/man3/gnutls_x509_crq_get_dn3.3
/usr/share/man/man3/gnutls_x509_crq_get_dn_by_oid.3
/usr/share/man/man3/gnutls_x509_crq_get_dn_oid.3
/usr/share/man/man3/gnutls_x509_crq_get_extension_by_oid.3
/usr/share/man/man3/gnutls_x509_crq_get_extension_by_oid2.3
/usr/share/man/man3/gnutls_x509_crq_get_extension_data.3
/usr/share/man/man3/gnutls_x509_crq_get_extension_data2.3
/usr/share/man/man3/gnutls_x509_crq_get_extension_info.3
/usr/share/man/man3/gnutls_x509_crq_get_key_id.3
/usr/share/man/man3/gnutls_x509_crq_get_key_purpose_oid.3
/usr/share/man/man3/gnutls_x509_crq_get_key_rsa_raw.3
/usr/share/man/man3/gnutls_x509_crq_get_key_usage.3
/usr/share/man/man3/gnutls_x509_crq_get_pk_algorithm.3
/usr/share/man/man3/gnutls_x509_crq_get_pk_oid.3
/usr/share/man/man3/gnutls_x509_crq_get_private_key_usage_period.3
/usr/share/man/man3/gnutls_x509_crq_get_signature_algorithm.3
/usr/share/man/man3/gnutls_x509_crq_get_signature_oid.3
/usr/share/man/man3/gnutls_x509_crq_get_spki.3
/usr/share/man/man3/gnutls_x509_crq_get_subject_alt_name.3
/usr/share/man/man3/gnutls_x509_crq_get_subject_alt_othername_oid.3
/usr/share/man/man3/gnutls_x509_crq_get_tlsfeatures.3
/usr/share/man/man3/gnutls_x509_crq_get_version.3
/usr/share/man/man3/gnutls_x509_crq_import.3
/usr/share/man/man3/gnutls_x509_crq_init.3
/usr/share/man/man3/gnutls_x509_crq_print.3
/usr/share/man/man3/gnutls_x509_crq_privkey_sign.3
/usr/share/man/man3/gnutls_x509_crq_set_attribute_by_oid.3
/usr/share/man/man3/gnutls_x509_crq_set_basic_constraints.3
/usr/share/man/man3/gnutls_x509_crq_set_challenge_password.3
/usr/share/man/man3/gnutls_x509_crq_set_dn.3
/usr/share/man/man3/gnutls_x509_crq_set_dn_by_oid.3
/usr/share/man/man3/gnutls_x509_crq_set_extension_by_oid.3
/usr/share/man/man3/gnutls_x509_crq_set_key.3
/usr/share/man/man3/gnutls_x509_crq_set_key_purpose_oid.3
/usr/share/man/man3/gnutls_x509_crq_set_key_rsa_raw.3
/usr/share/man/man3/gnutls_x509_crq_set_key_usage.3
/usr/share/man/man3/gnutls_x509_crq_set_private_key_usage_period.3
/usr/share/man/man3/gnutls_x509_crq_set_pubkey.3
/usr/share/man/man3/gnutls_x509_crq_set_spki.3
/usr/share/man/man3/gnutls_x509_crq_set_subject_alt_name.3
/usr/share/man/man3/gnutls_x509_crq_set_subject_alt_othername.3
/usr/share/man/man3/gnutls_x509_crq_set_tlsfeatures.3
/usr/share/man/man3/gnutls_x509_crq_set_version.3
/usr/share/man/man3/gnutls_x509_crq_sign.3
/usr/share/man/man3/gnutls_x509_crq_sign2.3
/usr/share/man/man3/gnutls_x509_crq_verify.3
/usr/share/man/man3/gnutls_x509_crt_check_email.3
/usr/share/man/man3/gnutls_x509_crt_check_hostname.3
/usr/share/man/man3/gnutls_x509_crt_check_hostname2.3
/usr/share/man/man3/gnutls_x509_crt_check_ip.3
/usr/share/man/man3/gnutls_x509_crt_check_issuer.3
/usr/share/man/man3/gnutls_x509_crt_check_key_purpose.3
/usr/share/man/man3/gnutls_x509_crt_check_revocation.3
/usr/share/man/man3/gnutls_x509_crt_cpy_crl_dist_points.3
/usr/share/man/man3/gnutls_x509_crt_deinit.3
/usr/share/man/man3/gnutls_x509_crt_equals.3
/usr/share/man/man3/gnutls_x509_crt_equals2.3
/usr/share/man/man3/gnutls_x509_crt_export.3
/usr/share/man/man3/gnutls_x509_crt_export2.3
/usr/share/man/man3/gnutls_x509_crt_get_activation_time.3
/usr/share/man/man3/gnutls_x509_crt_get_authority_info_access.3
/usr/share/man/man3/gnutls_x509_crt_get_authority_key_gn_serial.3
/usr/share/man/man3/gnutls_x509_crt_get_authority_key_id.3
/usr/share/man/man3/gnutls_x509_crt_get_basic_constraints.3
/usr/share/man/man3/gnutls_x509_crt_get_ca_status.3
/usr/share/man/man3/gnutls_x509_crt_get_crl_dist_points.3
/usr/share/man/man3/gnutls_x509_crt_get_dn.3
/usr/share/man/man3/gnutls_x509_crt_get_dn2.3
/usr/share/man/man3/gnutls_x509_crt_get_dn3.3
/usr/share/man/man3/gnutls_x509_crt_get_dn_by_oid.3
/usr/share/man/man3/gnutls_x509_crt_get_dn_oid.3
/usr/share/man/man3/gnutls_x509_crt_get_expiration_time.3
/usr/share/man/man3/gnutls_x509_crt_get_extension_by_oid.3
/usr/share/man/man3/gnutls_x509_crt_get_extension_by_oid2.3
/usr/share/man/man3/gnutls_x509_crt_get_extension_data.3
/usr/share/man/man3/gnutls_x509_crt_get_extension_data2.3
/usr/share/man/man3/gnutls_x509_crt_get_extension_info.3
/usr/share/man/man3/gnutls_x509_crt_get_extension_oid.3
/usr/share/man/man3/gnutls_x509_crt_get_fingerprint.3
/usr/share/man/man3/gnutls_x509_crt_get_inhibit_anypolicy.3
/usr/share/man/man3/gnutls_x509_crt_get_issuer.3
/usr/share/man/man3/gnutls_x509_crt_get_issuer_alt_name.3
/usr/share/man/man3/gnutls_x509_crt_get_issuer_alt_name2.3
/usr/share/man/man3/gnutls_x509_crt_get_issuer_alt_othername_oid.3
/usr/share/man/man3/gnutls_x509_crt_get_issuer_dn.3
/usr/share/man/man3/gnutls_x509_crt_get_issuer_dn2.3
/usr/share/man/man3/gnutls_x509_crt_get_issuer_dn3.3
/usr/share/man/man3/gnutls_x509_crt_get_issuer_dn_by_oid.3
/usr/share/man/man3/gnutls_x509_crt_get_issuer_dn_oid.3
/usr/share/man/man3/gnutls_x509_crt_get_issuer_unique_id.3
/usr/share/man/man3/gnutls_x509_crt_get_key_id.3
/usr/share/man/man3/gnutls_x509_crt_get_key_purpose_oid.3
/usr/share/man/man3/gnutls_x509_crt_get_key_usage.3
/usr/share/man/man3/gnutls_x509_crt_get_name_constraints.3
/usr/share/man/man3/gnutls_x509_crt_get_pk_algorithm.3
/usr/share/man/man3/gnutls_x509_crt_get_pk_dsa_raw.3
/usr/share/man/man3/gnutls_x509_crt_get_pk_ecc_raw.3
/usr/share/man/man3/gnutls_x509_crt_get_pk_gost_raw.3
/usr/share/man/man3/gnutls_x509_crt_get_pk_oid.3
/usr/share/man/man3/gnutls_x509_crt_get_pk_rsa_raw.3
/usr/share/man/man3/gnutls_x509_crt_get_policy.3
/usr/share/man/man3/gnutls_x509_crt_get_preferred_hash_algorithm.3
/usr/share/man/man3/gnutls_x509_crt_get_private_key_usage_period.3
/usr/share/man/man3/gnutls_x509_crt_get_proxy.3
/usr/share/man/man3/gnutls_x509_crt_get_raw_dn.3
/usr/share/man/man3/gnutls_x509_crt_get_raw_issuer_dn.3
/usr/share/man/man3/gnutls_x509_crt_get_serial.3
/usr/share/man/man3/gnutls_x509_crt_get_signature.3
/usr/share/man/man3/gnutls_x509_crt_get_signature_algorithm.3
/usr/share/man/man3/gnutls_x509_crt_get_signature_oid.3
/usr/share/man/man3/gnutls_x509_crt_get_spki.3
/usr/share/man/man3/gnutls_x509_crt_get_subject.3
/usr/share/man/man3/gnutls_x509_crt_get_subject_alt_name.3
/usr/share/man/man3/gnutls_x509_crt_get_subject_alt_name2.3
/usr/share/man/man3/gnutls_x509_crt_get_subject_alt_othername_oid.3
/usr/share/man/man3/gnutls_x509_crt_get_subject_key_id.3
/usr/share/man/man3/gnutls_x509_crt_get_subject_unique_id.3
/usr/share/man/man3/gnutls_x509_crt_get_tlsfeatures.3
/usr/share/man/man3/gnutls_x509_crt_get_version.3
/usr/share/man/man3/gnutls_x509_crt_import.3
/usr/share/man/man3/gnutls_x509_crt_import_pkcs11.3
/usr/share/man/man3/gnutls_x509_crt_import_url.3
/usr/share/man/man3/gnutls_x509_crt_init.3
/usr/share/man/man3/gnutls_x509_crt_list_import.3
/usr/share/man/man3/gnutls_x509_crt_list_import2.3
/usr/share/man/man3/gnutls_x509_crt_list_import_pkcs11.3
/usr/share/man/man3/gnutls_x509_crt_list_import_url.3
/usr/share/man/man3/gnutls_x509_crt_list_verify.3
/usr/share/man/man3/gnutls_x509_crt_print.3
/usr/share/man/man3/gnutls_x509_crt_privkey_sign.3
/usr/share/man/man3/gnutls_x509_crt_set_activation_time.3
/usr/share/man/man3/gnutls_x509_crt_set_authority_info_access.3
/usr/share/man/man3/gnutls_x509_crt_set_authority_key_id.3
/usr/share/man/man3/gnutls_x509_crt_set_basic_constraints.3
/usr/share/man/man3/gnutls_x509_crt_set_ca_status.3
/usr/share/man/man3/gnutls_x509_crt_set_crl_dist_points.3
/usr/share/man/man3/gnutls_x509_crt_set_crl_dist_points2.3
/usr/share/man/man3/gnutls_x509_crt_set_crq.3
/usr/share/man/man3/gnutls_x509_crt_set_crq_extension_by_oid.3
/usr/share/man/man3/gnutls_x509_crt_set_crq_extensions.3
/usr/share/man/man3/gnutls_x509_crt_set_dn.3
/usr/share/man/man3/gnutls_x509_crt_set_dn_by_oid.3
/usr/share/man/man3/gnutls_x509_crt_set_expiration_time.3
/usr/share/man/man3/gnutls_x509_crt_set_extension_by_oid.3
/usr/share/man/man3/gnutls_x509_crt_set_flags.3
/usr/share/man/man3/gnutls_x509_crt_set_inhibit_anypolicy.3
/usr/share/man/man3/gnutls_x509_crt_set_issuer_alt_name.3
/usr/share/man/man3/gnutls_x509_crt_set_issuer_alt_othername.3
/usr/share/man/man3/gnutls_x509_crt_set_issuer_dn.3
/usr/share/man/man3/gnutls_x509_crt_set_issuer_dn_by_oid.3
/usr/share/man/man3/gnutls_x509_crt_set_issuer_unique_id.3
/usr/share/man/man3/gnutls_x509_crt_set_key.3
/usr/share/man/man3/gnutls_x509_crt_set_key_purpose_oid.3
/usr/share/man/man3/gnutls_x509_crt_set_key_usage.3
/usr/share/man/man3/gnutls_x509_crt_set_name_constraints.3
/usr/share/man/man3/gnutls_x509_crt_set_pin_function.3
/usr/share/man/man3/gnutls_x509_crt_set_policy.3
/usr/share/man/man3/gnutls_x509_crt_set_private_key_usage_period.3
/usr/share/man/man3/gnutls_x509_crt_set_proxy.3
/usr/share/man/man3/gnutls_x509_crt_set_proxy_dn.3
/usr/share/man/man3/gnutls_x509_crt_set_pubkey.3
/usr/share/man/man3/gnutls_x509_crt_set_serial.3
/usr/share/man/man3/gnutls_x509_crt_set_spki.3
/usr/share/man/man3/gnutls_x509_crt_set_subject_alt_name.3
/usr/share/man/man3/gnutls_x509_crt_set_subject_alt_othername.3
/usr/share/man/man3/gnutls_x509_crt_set_subject_alternative_name.3
/usr/share/man/man3/gnutls_x509_crt_set_subject_key_id.3
/usr/share/man/man3/gnutls_x509_crt_set_subject_unique_id.3
/usr/share/man/man3/gnutls_x509_crt_set_tlsfeatures.3
/usr/share/man/man3/gnutls_x509_crt_set_version.3
/usr/share/man/man3/gnutls_x509_crt_sign.3
/usr/share/man/man3/gnutls_x509_crt_sign2.3
/usr/share/man/man3/gnutls_x509_crt_verify.3
/usr/share/man/man3/gnutls_x509_crt_verify_data2.3
/usr/share/man/man3/gnutls_x509_dn_deinit.3
/usr/share/man/man3/gnutls_x509_dn_export.3
/usr/share/man/man3/gnutls_x509_dn_export2.3
/usr/share/man/man3/gnutls_x509_dn_get_rdn_ava.3
/usr/share/man/man3/gnutls_x509_dn_get_str.3
/usr/share/man/man3/gnutls_x509_dn_get_str2.3
/usr/share/man/man3/gnutls_x509_dn_import.3
/usr/share/man/man3/gnutls_x509_dn_init.3
/usr/share/man/man3/gnutls_x509_dn_oid_known.3
/usr/share/man/man3/gnutls_x509_dn_oid_name.3
/usr/share/man/man3/gnutls_x509_dn_set_str.3
/usr/share/man/man3/gnutls_x509_ext_deinit.3
/usr/share/man/man3/gnutls_x509_ext_export_aia.3
/usr/share/man/man3/gnutls_x509_ext_export_authority_key_id.3
/usr/share/man/man3/gnutls_x509_ext_export_basic_constraints.3
/usr/share/man/man3/gnutls_x509_ext_export_crl_dist_points.3
/usr/share/man/man3/gnutls_x509_ext_export_inhibit_anypolicy.3
/usr/share/man/man3/gnutls_x509_ext_export_key_purposes.3
/usr/share/man/man3/gnutls_x509_ext_export_key_usage.3
/usr/share/man/man3/gnutls_x509_ext_export_name_constraints.3
/usr/share/man/man3/gnutls_x509_ext_export_policies.3
/usr/share/man/man3/gnutls_x509_ext_export_private_key_usage_period.3
/usr/share/man/man3/gnutls_x509_ext_export_proxy.3
/usr/share/man/man3/gnutls_x509_ext_export_subject_alt_names.3
/usr/share/man/man3/gnutls_x509_ext_export_subject_key_id.3
/usr/share/man/man3/gnutls_x509_ext_export_tlsfeatures.3
/usr/share/man/man3/gnutls_x509_ext_import_aia.3
/usr/share/man/man3/gnutls_x509_ext_import_authority_key_id.3
/usr/share/man/man3/gnutls_x509_ext_import_basic_constraints.3
/usr/share/man/man3/gnutls_x509_ext_import_crl_dist_points.3
/usr/share/man/man3/gnutls_x509_ext_import_inhibit_anypolicy.3
/usr/share/man/man3/gnutls_x509_ext_import_key_purposes.3
/usr/share/man/man3/gnutls_x509_ext_import_key_usage.3
/usr/share/man/man3/gnutls_x509_ext_import_name_constraints.3
/usr/share/man/man3/gnutls_x509_ext_import_policies.3
/usr/share/man/man3/gnutls_x509_ext_import_private_key_usage_period.3
/usr/share/man/man3/gnutls_x509_ext_import_proxy.3
/usr/share/man/man3/gnutls_x509_ext_import_subject_alt_names.3
/usr/share/man/man3/gnutls_x509_ext_import_subject_key_id.3
/usr/share/man/man3/gnutls_x509_ext_import_tlsfeatures.3
/usr/share/man/man3/gnutls_x509_ext_print.3
/usr/share/man/man3/gnutls_x509_key_purpose_deinit.3
/usr/share/man/man3/gnutls_x509_key_purpose_get.3
/usr/share/man/man3/gnutls_x509_key_purpose_init.3
/usr/share/man/man3/gnutls_x509_key_purpose_set.3
/usr/share/man/man3/gnutls_x509_name_constraints_add_excluded.3
/usr/share/man/man3/gnutls_x509_name_constraints_add_permitted.3
/usr/share/man/man3/gnutls_x509_name_constraints_check.3
/usr/share/man/man3/gnutls_x509_name_constraints_check_crt.3
/usr/share/man/man3/gnutls_x509_name_constraints_deinit.3
/usr/share/man/man3/gnutls_x509_name_constraints_get_excluded.3
/usr/share/man/man3/gnutls_x509_name_constraints_get_permitted.3
/usr/share/man/man3/gnutls_x509_name_constraints_init.3
/usr/share/man/man3/gnutls_x509_othername_to_virtual.3
/usr/share/man/man3/gnutls_x509_policies_deinit.3
/usr/share/man/man3/gnutls_x509_policies_get.3
/usr/share/man/man3/gnutls_x509_policies_init.3
/usr/share/man/man3/gnutls_x509_policies_set.3
/usr/share/man/man3/gnutls_x509_policy_release.3
/usr/share/man/man3/gnutls_x509_privkey_cpy.3
/usr/share/man/man3/gnutls_x509_privkey_deinit.3
/usr/share/man/man3/gnutls_x509_privkey_export.3
/usr/share/man/man3/gnutls_x509_privkey_export2.3
/usr/share/man/man3/gnutls_x509_privkey_export2_pkcs8.3
/usr/share/man/man3/gnutls_x509_privkey_export_dsa_raw.3
/usr/share/man/man3/gnutls_x509_privkey_export_ecc_raw.3
/usr/share/man/man3/gnutls_x509_privkey_export_gost_raw.3
/usr/share/man/man3/gnutls_x509_privkey_export_pkcs8.3
/usr/share/man/man3/gnutls_x509_privkey_export_rsa_raw.3
/usr/share/man/man3/gnutls_x509_privkey_export_rsa_raw2.3
/usr/share/man/man3/gnutls_x509_privkey_fix.3
/usr/share/man/man3/gnutls_x509_privkey_generate.3
/usr/share/man/man3/gnutls_x509_privkey_generate2.3
/usr/share/man/man3/gnutls_x509_privkey_get_key_id.3
/usr/share/man/man3/gnutls_x509_privkey_get_pk_algorithm.3
/usr/share/man/man3/gnutls_x509_privkey_get_pk_algorithm2.3
/usr/share/man/man3/gnutls_x509_privkey_get_seed.3
/usr/share/man/man3/gnutls_x509_privkey_get_spki.3
/usr/share/man/man3/gnutls_x509_privkey_import.3
/usr/share/man/man3/gnutls_x509_privkey_import2.3
/usr/share/man/man3/gnutls_x509_privkey_import_dsa_raw.3
/usr/share/man/man3/gnutls_x509_privkey_import_ecc_raw.3
/usr/share/man/man3/gnutls_x509_privkey_import_gost_raw.3
/usr/share/man/man3/gnutls_x509_privkey_import_openssl.3
/usr/share/man/man3/gnutls_x509_privkey_import_pkcs8.3
/usr/share/man/man3/gnutls_x509_privkey_import_rsa_raw.3
/usr/share/man/man3/gnutls_x509_privkey_import_rsa_raw2.3
/usr/share/man/man3/gnutls_x509_privkey_init.3
/usr/share/man/man3/gnutls_x509_privkey_sec_param.3
/usr/share/man/man3/gnutls_x509_privkey_set_flags.3
/usr/share/man/man3/gnutls_x509_privkey_set_pin_function.3
/usr/share/man/man3/gnutls_x509_privkey_set_spki.3
/usr/share/man/man3/gnutls_x509_privkey_sign_data.3
/usr/share/man/man3/gnutls_x509_privkey_sign_hash.3
/usr/share/man/man3/gnutls_x509_privkey_verify_params.3
/usr/share/man/man3/gnutls_x509_privkey_verify_seed.3
/usr/share/man/man3/gnutls_x509_rdn_get.3
/usr/share/man/man3/gnutls_x509_rdn_get2.3
/usr/share/man/man3/gnutls_x509_rdn_get_by_oid.3
/usr/share/man/man3/gnutls_x509_rdn_get_oid.3
/usr/share/man/man3/gnutls_x509_spki_deinit.3
/usr/share/man/man3/gnutls_x509_spki_get_rsa_pss_params.3
/usr/share/man/man3/gnutls_x509_spki_init.3
/usr/share/man/man3/gnutls_x509_spki_set_rsa_pss_params.3
/usr/share/man/man3/gnutls_x509_tlsfeatures_add.3
/usr/share/man/man3/gnutls_x509_tlsfeatures_check_crt.3
/usr/share/man/man3/gnutls_x509_tlsfeatures_deinit.3
/usr/share/man/man3/gnutls_x509_tlsfeatures_get.3
/usr/share/man/man3/gnutls_x509_tlsfeatures_init.3
/usr/share/man/man3/gnutls_x509_trust_list_add_cas.3
/usr/share/man/man3/gnutls_x509_trust_list_add_crls.3
/usr/share/man/man3/gnutls_x509_trust_list_add_named_crt.3
/usr/share/man/man3/gnutls_x509_trust_list_add_system_trust.3
/usr/share/man/man3/gnutls_x509_trust_list_add_trust_dir.3
/usr/share/man/man3/gnutls_x509_trust_list_add_trust_file.3
/usr/share/man/man3/gnutls_x509_trust_list_add_trust_mem.3
/usr/share/man/man3/gnutls_x509_trust_list_deinit.3
/usr/share/man/man3/gnutls_x509_trust_list_get_issuer.3
/usr/share/man/man3/gnutls_x509_trust_list_get_issuer_by_dn.3
/usr/share/man/man3/gnutls_x509_trust_list_get_issuer_by_subject_key_id.3
/usr/share/man/man3/gnutls_x509_trust_list_init.3
/usr/share/man/man3/gnutls_x509_trust_list_iter_deinit.3
/usr/share/man/man3/gnutls_x509_trust_list_iter_get_ca.3
/usr/share/man/man3/gnutls_x509_trust_list_remove_cas.3
/usr/share/man/man3/gnutls_x509_trust_list_remove_trust_file.3
/usr/share/man/man3/gnutls_x509_trust_list_remove_trust_mem.3
/usr/share/man/man3/gnutls_x509_trust_list_verify_crt.3
/usr/share/man/man3/gnutls_x509_trust_list_verify_crt2.3
/usr/share/man/man3/gnutls_x509_trust_list_verify_named_crt.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libgnutls.so
/usr/lib32/libgnutlsxx.so
/usr/lib32/pkgconfig/32gnutls.pc
/usr/lib32/pkgconfig/gnutls.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/gnutls/*

%files extras
%defattr(-,root,root,-)
/usr/lib64/libgnutlsxx.so
/usr/lib64/libgnutlsxx.so.28
/usr/lib64/libgnutlsxx.so.28.1.0

%files info
%defattr(0644,root,root,0755)
/usr/share/info/gnutls-client-server-use-case.png
/usr/share/info/gnutls-guile.info
/usr/share/info/gnutls-handshake-sequence.png
/usr/share/info/gnutls-handshake-state.png
/usr/share/info/gnutls-internals.png
/usr/share/info/gnutls-layers.png
/usr/share/info/gnutls-logo.png
/usr/share/info/gnutls-modauth.png
/usr/share/info/gnutls-x509.png
/usr/share/info/gnutls.info
/usr/share/info/gnutls.info-1
/usr/share/info/gnutls.info-2
/usr/share/info/gnutls.info-3
/usr/share/info/gnutls.info-4
/usr/share/info/gnutls.info-5
/usr/share/info/gnutls.info-6
/usr/share/info/gnutls.info-7
/usr/share/info/pkcs11-vision.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgnutls.so.30
/usr/lib64/libgnutls.so.30.28.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libgnutls.so.30
/usr/lib32/libgnutls.so.30.28.0
/usr/lib32/libgnutlsxx.so.28
/usr/lib32/libgnutlsxx.so.28.1.0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/certtool.1
/usr/share/man/man1/gnutls-cli-debug.1
/usr/share/man/man1/gnutls-cli.1
/usr/share/man/man1/gnutls-serv.1
/usr/share/man/man1/ocsptool.1
/usr/share/man/man1/p11tool.1
/usr/share/man/man1/psktool.1
/usr/share/man/man1/srptool.1
/usr/share/man/man1/tpmtool.1

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libgnutls.a
/usr/lib64/libgnutlsxx.a

%files staticdev32
%defattr(-,root,root,-)
/usr/lib32/libgnutls.a
/usr/lib32/libgnutlsxx.a

%files locales -f gnutls.lang
%defattr(-,root,root,-)

